### ISSUE TITLE
Move components from `reakit` to `radix-ui`

### ISSUE THREAD

**Issue by tommoor** [outline/outline#6456]
`Reakit` is dead, `Radix` won.

Sometimes we bet on the wrong frameworks and that's definitely what happened here – [shadcn](https://ui.shadcn.com/) provides some great boilerplate to make moving across easier, combining the parts of Radix into usable UI components. We should move Outline's components one by one to radix, in particular:

- [x] `InputSelect`
- [x] `VisuallyHidden`
- [x] `Tooltip`
- [x] `Switch`
- [x] `Modal`
- [x] `Popover`
- [x] `ViewReactionsDialog`
- [x] `Guide`
- [x] `SearchPopover`
- [x] `SkinTonePicker`
- [x] `ContextMenu`
- [x] `FilterOptions`
- [x] `ToolbarMenu`

---

- [x] Remove old Radix components and lib
- [ ] Rename `V2` menu variants

The context menu will be a relatively large undertaking and as such, should be left until last.

**Comment by tommoor** [comment]
### InputSelect

- [x] DefaultCollectionInputSelect (#8541)
- [x] Details (Settings)(ToC preference) (#8541)
- [x] CommentSortMenu (#8541)
- [x] Preferences (Settings)(Language and theme preferences) (#8711)
- [x] Security (Settings)(Default role for new users) (#8711)
- [x] InputSelectPermission (#9585)
- [x] InputMemberPermissionSelect (#9599)
- [x] SelectLocation (TemplatizeDialog) (#9599)
- [x] ApiKeyNew (#9599)
- [x] Invite (#9599)
